namespace Microsoft.ReportingServices.Rendering.RichText
{
	internal enum ScriptJustify
	{
		SCRIPT_JUSTIFY_NONE,
		SCRIPT_JUSTIFY_ARABIC_BLANK,
		SCRIPT_JUSTIFY_CHARACTER,
		SCRIPT_JUSTIFY_RESERVED1,
		SCRIPT_JUSTIFY_BLANK,
		SCRIPT_JUSTIFY_RESERVED2,
		SCRIPT_JUSTIFY_RESERVED3,
		SCRIPT_JUSTIFY_ARABIC_NORMAL,
		SCRIPT_JUSTIFY_ARABIC_KASHIDA,
		SCRIPT_JUSTIFY_ARABIC_ALEF,
		SCRIPT_JUSTIFY_ARABIC_HA,
		SCRIPT_JUSTIFY_ARABIC_RA,
		SCRIPT_JUSTIFY_ARABIC_BA,
		SCRIPT_JUSTIFY_ARABIC_BARA,
		SCRIPT_JUSTIFY_ARABIC_SEEN,
		SCRIPT_JUSTIFY_ARABIC_SEEN_M
	}
}
