using System.Collections.Generic;

namespace Microsoft.ReportingServices.Common
{
	internal static class RdlCollations
	{
		private static Dictionary<string, uint> m_sqlCollations2LCID;

		internal static Dictionary<string, uint> Collations => m_sqlCollations2LCID;

		static RdlCollations()
		{
			List<KeyValuePair<string, uint>> obj = new List<KeyValuePair<string, uint>>
			{
				new KeyValuePair<string, uint>("Albanian", 1052u),
				new KeyValuePair<string, uint>("Albanian_100", 1052u),
				new KeyValuePair<string, uint>("Amharic_100", 1067u),
				new KeyValuePair<string, uint>("Arabic", 1025u),
				new KeyValuePair<string, uint>("Arabic_100", 1025u),
				new KeyValuePair<string, uint>("Armenian_100", 1067u),
				new KeyValuePair<string, uint>("Assamese_100", 1101u),
				new KeyValuePair<string, uint>("Azeri_Cyrillic_90", 2092u),
				new KeyValuePair<string, uint>("Azeri_Cyrillic_100", 2092u),
				new KeyValuePair<string, uint>("Azeri_Latin_90", 1068u),
				new KeyValuePair<string, uint>("Azeri_Latin_100", 1068u),
				new KeyValuePair<string, uint>("Bashkir_100", 1133u),
				new KeyValuePair<string, uint>("Bengali_100", 1081u),
				new KeyValuePair<string, uint>("Bosnian_Cyrillic_100", 1026u),
				new KeyValuePair<string, uint>("Bosnian_Latin_100", 1050u),
				new KeyValuePair<string, uint>("Breton_100", 1150u),
				new KeyValuePair<string, uint>("Chinese_Hong_Kong_Stroke_90", 3076u),
				new KeyValuePair<string, uint>("Chinese_Hong_Kong_Stroke_100", 3076u),
				new KeyValuePair<string, uint>("Chinese_Macao_100", 5124u),
				new KeyValuePair<string, uint>("Chinese_Macao_Stroke_100", 136196u),
				new KeyValuePair<string, uint>("Chinese_PRC", 2052u),
				new KeyValuePair<string, uint>("Chinese_PRC_100", 2052u),
				new KeyValuePair<string, uint>("Chinese_PRC_Stroke", 133124u),
				new KeyValuePair<string, uint>("Chinese_PRC_Stroke_100", 133124u),
				new KeyValuePair<string, uint>("Chinese_Simplified_Pinyin_100", 2052u),
				new KeyValuePair<string, uint>("Chinese_Simplified_Stroke_Order_100", 133124u),
				new KeyValuePair<string, uint>("Chinese_Taiwan_Bopomofo", 197636u),
				new KeyValuePair<string, uint>("Chinese_Taiwan_Bopomofo_100", 197636u),
				new KeyValuePair<string, uint>("Chinese_Taiwan_Stroke", 1028u),
				new KeyValuePair<string, uint>("Chinese_Taiwan_Stroke_100", 1028u),
				new KeyValuePair<string, uint>("Chinese_Traditional_Bopomofo_100", 197636u),
				new KeyValuePair<string, uint>("Chinese_Traditional_Pinyin_100", 5124u),
				new KeyValuePair<string, uint>("Chinese_Traditional_Stroke_Count_100", 1028u),
				new KeyValuePair<string, uint>("Chinese_Traditional_Stroke_Order_100", 136196u),
				new KeyValuePair<string, uint>("Corsican_100", 1155u),
				new KeyValuePair<string, uint>("Croatian", 1050u),
				new KeyValuePair<string, uint>("Croatian_100", 1050u),
				new KeyValuePair<string, uint>("Cyrillic_General", 1049u),
				new KeyValuePair<string, uint>("Cyrillic_General_100", 1049u),
				new KeyValuePair<string, uint>("Czech", 1029u),
				new KeyValuePair<string, uint>("Czech_100", 1029u),
				new KeyValuePair<string, uint>("Danish_Greenlandic_100", 1030u),
				new KeyValuePair<string, uint>("Danish_Norwegian", 1030u),
				new KeyValuePair<string, uint>("Dari_100", 1164u),
				new KeyValuePair<string, uint>("Divehi_90", 1125u),
				new KeyValuePair<string, uint>("Divehi_100", 1125u),
				new KeyValuePair<string, uint>("Estonian", 1061u),
				new KeyValuePair<string, uint>("Estonian_100", 1061u),
				new KeyValuePair<string, uint>("Finnish_Swedish", 1035u),
				new KeyValuePair<string, uint>("Finnish_Swedish_100", 1035u),
				new KeyValuePair<string, uint>("French", 1036u),
				new KeyValuePair<string, uint>("French_100", 1036u),
				new KeyValuePair<string, uint>("Frisian_100", 1122u),
				new KeyValuePair<string, uint>("Georgian_Modern_Sort", 66615u),
				new KeyValuePair<string, uint>("Georgian_Traditional_100", 1067u),
				new KeyValuePair<string, uint>("German_PhoneBook", 66567u),
				new KeyValuePair<string, uint>("German_PhoneBook_100", 66567u),
				new KeyValuePair<string, uint>("Greek", 1032u),
				new KeyValuePair<string, uint>("Greek_100", 1032u),
				new KeyValuePair<string, uint>("Hebrew", 1037u),
				new KeyValuePair<string, uint>("Hebrew_100", 1037u),
				new KeyValuePair<string, uint>("Hindi", 1081u),
				new KeyValuePair<string, uint>("Hungarian", 1038u),
				new KeyValuePair<string, uint>("Hungarian_100", 1038u),
				new KeyValuePair<string, uint>("Hungarian_Technical", 66574u),
				new KeyValuePair<string, uint>("Hungarian_Technical_100", 66574u),
				new KeyValuePair<string, uint>("Icelandic", 1039u),
				new KeyValuePair<string, uint>("Icelandic_100", 1039u),
				new KeyValuePair<string, uint>("Indic_General_90", 1081u),
				new KeyValuePair<string, uint>("Indic_General_100", 1081u),
				new KeyValuePair<string, uint>("Inuktitut_100", 1027u),
				new KeyValuePair<string, uint>("Japanese", 1041u),
				new KeyValuePair<string, uint>("Japanese_90", 1041u),
				new KeyValuePair<string, uint>("Japanese_100", 1041u),
				new KeyValuePair<string, uint>("Japanese_Bushu_Kakusu_100", 263185u),
				new KeyValuePair<string, uint>("Japanese_Radical_Stroke_100", 263185u),
				new KeyValuePair<string, uint>("Japanese_Unicode", 66577u),
				new KeyValuePair<string, uint>("Kazakh_90", 1087u),
				new KeyValuePair<string, uint>("Kazakh_100", 1087u),
				new KeyValuePair<string, uint>("Khmer_100", 1107u),
				new KeyValuePair<string, uint>("Korean", 1042u),
				new KeyValuePair<string, uint>("Korean_90", 1042u),
				new KeyValuePair<string, uint>("Korean_100", 1042u),
				new KeyValuePair<string, uint>("Korean_Wansung", 1042u),
				new KeyValuePair<string, uint>("Korean_Wansung_Unicode", 66578u),
				new KeyValuePair<string, uint>("Lao_100", 1108u),
				new KeyValuePair<string, uint>("Latin1_General", 1033u),
				new KeyValuePair<string, uint>("Latin1_General_100", 1033u),
				new KeyValuePair<string, uint>("Latvian", 1062u),
				new KeyValuePair<string, uint>("Latvian_100", 1062u),
				new KeyValuePair<string, uint>("Lithuanian", 1063u),
				new KeyValuePair<string, uint>("Lithuanian_100", 1063u),
				new KeyValuePair<string, uint>("Lithuanian_Classic", 2087u),
				new KeyValuePair<string, uint>("Macedonian", 1071u),
				new KeyValuePair<string, uint>("Macedonian_FYROM_90", 1071u),
				new KeyValuePair<string, uint>("Macedonian_FYROM_100", 1071u),
				new KeyValuePair<string, uint>("Maltese_100", 1082u),
				new KeyValuePair<string, uint>("Maori_100", 1153u),
				new KeyValuePair<string, uint>("Mapudungan_100", 1146u),
				new KeyValuePair<string, uint>("Modern_Spanish", 3082u),
				new KeyValuePair<string, uint>("Modern_Spanish_100", 3082u),
				new KeyValuePair<string, uint>("Mohawk_100", 1148u),
				new KeyValuePair<string, uint>("Mongolian_100", 1067u),
				new KeyValuePair<string, uint>("Nepali_100", 1121u),
				new KeyValuePair<string, uint>("Norwegian_100", 1044u),
				new KeyValuePair<string, uint>("Norwegian_Sami_100", 1083u),
				new KeyValuePair<string, uint>("Pashto_100", 1123u),
				new KeyValuePair<string, uint>("Persian_100", 1065u),
				new KeyValuePair<string, uint>("Polish", 1045u),
				new KeyValuePair<string, uint>("Polish_100", 1045u),
				new KeyValuePair<string, uint>("Romanian", 1048u),
				new KeyValuePair<string, uint>("Romanian_100", 1048u),
				new KeyValuePair<string, uint>("Romansh_100", 1047u),
				new KeyValuePair<string, uint>("Sami_Norway_100", 1083u),
				new KeyValuePair<string, uint>("Sami_Sweden_Finland_100", 2107u),
				new KeyValuePair<string, uint>("Serbian_Cyrillic_100", 3098u),
				new KeyValuePair<string, uint>("Serbian_Latin_100", 1050u),
				new KeyValuePair<string, uint>("Slovak", 1051u),
				new KeyValuePair<string, uint>("Slovak_100", 1051u),
				new KeyValuePair<string, uint>("Slovenian", 1060u),
				new KeyValuePair<string, uint>("Slovenian_100", 1060u),
				new KeyValuePair<string, uint>("Swedish_Finnish_Sami_100", 1035u),
				new KeyValuePair<string, uint>("Syriac_90", 1114u),
				new KeyValuePair<string, uint>("Syriac_100", 1114u),
				new KeyValuePair<string, uint>("Tatar_90", 1092u),
				new KeyValuePair<string, uint>("Tatar_100", 1092u),
				new KeyValuePair<string, uint>("Tamazight_100", 2143u),
				new KeyValuePair<string, uint>("Thai", 1054u),
				new KeyValuePair<string, uint>("Thai_100", 1054u),
				new KeyValuePair<string, uint>("Tibetan_PRC_100", 1105u),
				new KeyValuePair<string, uint>("Traditional_Spanish", 1034u),
				new KeyValuePair<string, uint>("Traditional_Spanish_100", 1034u),
				new KeyValuePair<string, uint>("Turkish", 1055u),
				new KeyValuePair<string, uint>("Turkish_100", 1055u),
				new KeyValuePair<string, uint>("Turkmen_100", 1090u),
				new KeyValuePair<string, uint>("Uighur_PRC_100", 1152u),
				new KeyValuePair<string, uint>("Ukrainian", 1058u),
				new KeyValuePair<string, uint>("Ukrainian_100", 1058u),
				new KeyValuePair<string, uint>("Upper_Sorbian_100", 1070u),
				new KeyValuePair<string, uint>("Urdu_100", 1056u),
				new KeyValuePair<string, uint>("Uzbek_Latin_90", 1091u),
				new KeyValuePair<string, uint>("Uzbek_Latin_100", 1091u),
				new KeyValuePair<string, uint>("Vietnamese", 1066u),
				new KeyValuePair<string, uint>("Vietnamese_100", 1066u),
				new KeyValuePair<string, uint>("Welsh_100", 1106u),
				new KeyValuePair<string, uint>("Yakut_100", 1157u),
				new KeyValuePair<string, uint>("Yi_100", 1067u)
			};
			m_sqlCollations2LCID = new Dictionary<string, uint>(obj.Count);
			foreach (KeyValuePair<string, uint> item in obj)
			{
				m_sqlCollations2LCID.Add(item.Key, item.Value);
			}
		}
	}
}
